Add changes from upstream (#10)
* Fix for AttributeError: 'TuyaMessage' object has no attribute 'release' error

* #711 Implemented m/p HVAC mode set

* Introduced pytuya with support for 3.4 protocol

* Introduced 3.4 protocol option in config flow

* Fixed HEARTBEAT command

* Added debugging

* Fixed requested DPs for type_0d devices

* Fixed negotiation and sequence numbers for protocol 3.4

* Fixed sequence numbering on status update

* Fixed tox issues

* Fixed tox issues

* Updated README.md and info.md

* Fixed tox issues

* Fix for version not being set yet when calling _setup_dispatcher

* Introduced the possibility to select which devices should have the pytuya debug enabled

* Introduced device debugging option in README.md and info.md

* Introduced pytuya with support for 3.4 protocol

* Introduced 3.4 protocol option in config flow

* Fixed HEARTBEAT command

* Added debugging

* Fixed requested DPs for type_0d devices

* Fixed negotiation and sequence numbers for protocol 3.4

* Fixed sequence numbering on status update

* Fixed tox issues

* Fixed tox issues

* Updated README.md and info.md

* Fixed tox issues

* Fix for version not being set yet when calling _setup_dispatcher

* Introduced abort in config flow if all entities are deselected when editing a device

* Introduced IT and PT translations

* Update manifest.json for 5.0.0

* New tuyadebug.tgz now supporting protocol 3.4

* Update bug_report.md

* Fix for unknown state of covers/shutters

* New tuyadebug.tgz now including a tinytuya test

* Force to int

* Adjust input to avoid putting a string into an int

* Adjust input to avoid putting a string into an int

* Swap to int

* Improved logging

* Improved stability and Fix local_key update to not be thwarted by retries

* Introduced update of local_key when editing a device

* Improved logging

* Tox fixes

* Tox fixes

* Tox fixes

* Fix for not reconnecting after 'giving up'

* Tox fixes

* Tox fixes, reduced to 3.9 only

* Add entities during 'Edit a device'

* revert the default region

* Fix depreciated async_get_registry

* Add HACS validation

* Remove extra key

* Update manifest.json

* Remove extra key

* Update hacs.json

* Add Hassfest validation

* Alphabetize manifest.json

Alphabetized manifest.json according to home assistant requirements.

* Delete combined.yaml

As described in KTibow/ha-blueprint, ha-blueprint is being retired and we should thereby switch over to hassfest and hacs validation.

* Update tox.yaml

Added workflow_dispatch

* Update tox.ini

* Reduced logging level for 'Command %d timed out waiting for sequence number'; set v.5.1.0

* Fixed tox errors

* Updated manifest.json

* Fix for socket.send() exceptions in the logs

* Fixing pylint error

* fix bug when climate entity is using default min/max temp and temp unit is F

The default min/max temps are in C but when the climate entity is set up with F this will cause incorrect boundary check and an inability to change the temperature from the home assistant entity UI widget.

* Allow calling localtuya.set_dp service by non-admin users

* Fixed initialization with API but no internet.

* Handle 3.4 protocol, fix CI (#1251)

* Use refresh interval in version 3.4
* Scan interval convert to integer
* Try to fix CI
* Try to fix CI

* Allow port reuse so that other integrations can read the same port (#1481)

Co-authored-by: rospogrigio <49229287+rospogrigio@users.noreply.github.com>

* Fixing tox issues

* Replaced SUPPORT_* with enums, set minimum HA version in HACS configuration to 2024.1.0

* Add support for more ac/fan modes (#1389)

* Add support for more ac/fan modes

* Replace deprecated constants with enums

* Add support for ClimateEntityFeature.TURN_{ON,OFF}

* Fix swing log message

---------

Co-authored-by: Simon Tegelid <simon.tegelid@bitvis.io>

* added dict get() instead of assuming keys exist; now handles config_flow setup failures without crashing

* feat: add climate entity support for Comfortbilt stoves

* refactor: change information for fork

* feat: add support for alarm

---------

Co-authored-by: sibowler <simon@bowler.id.au>
Co-authored-by: Daan Kemper <info@daankemper.nl>
Co-authored-by: rospogrigio <49229287+rospogrigio@users.noreply.github.com>
Co-authored-by: rospogrigio <rospogrigio@gmail.com>
Co-authored-by: Daniel O'Connor <daniel.oconnor@gmail.com>
Co-authored-by: GaoJing <270615179@qq.com>
Co-authored-by: oven-lab <waldemar.bjornstrom@unfnorrbotten.se>
Co-authored-by: nu <2722344+ncd7@users.noreply.github.com>
Co-authored-by: Ovidiu Nitan <nitanovidiu@gmail.com>
Co-authored-by: Neal Joslin <Nealiumj@gmail.com>
Co-authored-by: dulyts <jobb.gabor@gmail.com>
Co-authored-by: Luke Bonaccorsi <luke@lukeb.co.uk>
Co-authored-by: Elad Bar <elad.bar@hotmail.com>
Co-authored-by: Simon Tegelid <simon@tegelid.se>
Co-authored-by: Simon Tegelid <simon.tegelid@bitvis.io>
Co-authored-by: hello@theauthtoken.com <rsnodgrass@gmail.com>